name       : networkmanager-openvpn
version    : 1.8.2
release    : 14
source     :
    - https://download.gnome.org/sources/NetworkManager-openvpn/1.8/NetworkManager-openvpn-1.8.2.tar.xz : 8861afd1f369a55e5d229228370bf63c08cc4e987bcf29d36c410618d094375d
license    : GPL-2.0
summary    : OpenVPN plugin for NetworkManager
description: |
    OpenVPN plugin for NetworkManager allows you to manage openvpn connections from the network manager applet.
component  : network.base
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnm-gtk)
    - pkgconfig(libsecret-unstable)
rundeps    :
    - openvpn
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/nm-openvpn.sysusers $installdir/%libdir%/sysusers.d/nm-openvpn.conf
