name       : networkmanager-openvpn
version    : 1.8.4
release    : 15
source     :
    - https://download.gnome.org/sources/NetworkManager-openvpn/1.8/NetworkManager-openvpn-1.8.4.tar.xz : 79b7252a4af51381824816ea13223457ad7e3fc14c6144aac727cc040dd9d93f
license    : GPL-2.0-only
summary    : OpenVPN plugin for NetworkManager
description: |
    OpenVPN plugin for NetworkManager allows you to manage openvpn connections from the network manager applet.
component  : network.base
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnm-gtk)
    - pkgconfig(libsecret-unstable)
rundeps    :
    - openvpn
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/nm-openvpn.sysusers $installdir/%libdir%/sysusers.d/nm-openvpn.conf
