name       : networkmanager-openvpn
version    : 1.2.10
release    : 9
source     :
    - https://ftp.gnome.org/pub/gnome/sources/NetworkManager-openvpn/1.2/NetworkManager-openvpn-1.2.10.tar.xz : ac86a7a539d78df90095676e9183f2d422fb93dbfe4b3afef22f81825d303d61
license    : GPL-2.0
summary    : OpenVPN plugin for NetworkManager
description: |
    OpenVPN plugin for NetworkManager allows you to manage openvpn connections from the network manager applet.
component  : network.base
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnm-gtk)
    - pkgconfig(libsecret-unstable)
rundeps    :
    - openvpn
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/nm-openvpn.sysusers $installdir/%libdir%/sysusers.d/nm-openvpn.conf
