name       : networkmanager-openvpn
version    : 1.2.6
release    : 4
source     :
    - https://ftp.gnome.org/pub/gnome/sources/NetworkManager-openvpn/1.2/NetworkManager-openvpn-1.2.6.tar.xz : 2373e2bb0a8a876cb2997cd8b0e3d6e10012d9bef3705ea3ac21f6394b3f1fb0
license    : GPL-2.0
summary    : OpenVPN plugin for NetworkManager
description: |
    OpenVPN plugin for NetworkManager allows you to manage openvpn connections from the network manager applet.
component  : network.base
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnm-gtk)
    - pkgconfig(libsecret-unstable)
rundeps    :
    - openvpn
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
