name       : networkmanager-openvpn
version    : 1.0.2
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/NetworkManager-openvpn/1.0/NetworkManager-openvpn-1.0.2.tar.xz : 1643824bc7fdab42e1dab836bf81c328692295c86f146bde602eca093b394bb0
license    : GPL-2.0
summary    : OpenVPN plugin for NetworkManager
description: |
    OpenVPN plugin for NetworkManager allows you to manage openvpn connections from the network manager applet.
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnm-gtk)
    - pkgconfig(libsecret-unstable)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
