name       : networkmanager-openvpn
version    : 1.8.0
release    : 13
source     :
    - git|git://git.gnome.org/network-manager-openvpn : e4d8cda14483b3195dbf2a9d61c565f426108ea3
license    : GPL-2.0
summary    : OpenVPN plugin for NetworkManager
description: |
    OpenVPN plugin for NetworkManager allows you to manage openvpn connections from the network manager applet.
component  : network.base
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnm-gtk)
    - pkgconfig(libsecret-unstable)
rundeps    :
    - openvpn
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/nm-openvpn.sysusers $installdir/%libdir%/sysusers.d/nm-openvpn.conf
