name       : networkmanager-openvpn
version    : 1.8.14
release    : 24
source     :
    - https://download.gnome.org/sources/NetworkManager-openvpn/1.8/NetworkManager-openvpn-1.8.14.tar.xz : e7419053fc3b5a7e25f1a7517c313ad4531b6ea280255524ebb85a70c76fdbeb
license    : GPL-2.0-or-later
summary    : OpenVPN plugin for NetworkManager
description: |
    OpenVPN plugin for NetworkManager allows you to manage openvpn connections from the network manager applet.
component  : network.base
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnma)
    - pkgconfig(libsecret-unstable)
rundeps    :
    - openvpn
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/nm-openvpn.sysusers $installdir/%libdir%/sysusers.d/nm-openvpn.conf
